name: Cypress Tests

on: push

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: "cypress:protocol:capture,cypress:server:util:process_profiler"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

  electron-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Testing in Electron"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          record: true
          parallel: true
          group: "Electron"

  chrome-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Testing in Chrome"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          browser: chrome
          record: true
          parallel: true
          group: "Chrome"

  firefox-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Testing in Firefox"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          browser: firefox
          record: true
          parallel: true
          group: "Firefox"

  edge-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Testing in Edge"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          browser: edge
          record: true
          parallel: true
          group: "Edge"

  webkit-browser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Playwright dependencies for WebKit
        run: npx playwright install-deps webkit

      - name: "Testing in WebKit"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          browser: webkit
          record: true
          parallel: true
          group: "WebKit"
          config: "experimentalWebKitSupport=true"